name: main

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date
  job2:
    runs-on: windows-latest
    steps:
      - name: print date
        run: date
  job3:
    runs-on: macos-latest
    steps:
      - name: print date
        run: date
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: print date
        run: date
