name: solution

env: 
  FILE_NAME: 'custom-artifact'

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE_NAME }}
          path: ./${{ env.FILE_NAME }}


